export const CAMPUS_BUILDINGS = [
    {
        id: 'library',
        name: { zh: '图书馆', en: 'Library' },
        width: 30, depth: 25, height: 20,
        color: 0x50c878,
        position: { x: -60, y: 0, z: 50 },
        roofType: 'pointed',
        windows: { rows: 4, cols: 5 },
        mood: 'hot',
        emotionLabel: { zh: '午后最热的角落', en: 'Hottest Corner in Afternoon' },
    },
    {
        id: 'info-building',
        name: { zh: '信息楼', en: 'Information Building' },
        width: 25, depth: 20, height: 30,
        color: 0x4a90d9,
        position: { x: -50, y: 0, z: -20 },
        roofType: 'flat',
        windows: { rows: 5, cols: 6 },
        mood: 'wet',
        emotionLabel: { zh: '下雨天没有遮挡的路', en: 'Unsheltered Path on Rainy Days' },
    },
    {
        id: 'energy-building',
        name: { zh: '能源楼', en: 'Energy Building' },
        width: 20, depth: 18, height: 25,
        color: 0x9b59b6,
        position: { x: -10, y: 0, z: -40 },
        roofType: 'dome',
        windows: { rows: 4, cols: 4 },
        mood: 'quiet',
        emotionLabel: { zh: '没人去的好地方', en: 'Hidden Gem Quiet Spot' },
    },
    {
        id: 'intl-center',
        name: { zh: '国际中心', en: 'International Center' },
        width: 28, depth: 22, height: 22,
        color: 0x1abc9c,
        position: { x: 30, y: 0, z: 50 },
        roofType: 'flat',
        windows: { rows: 4, cols: 5 },
        mood: 'noisy',
        emotionLabel: { zh: '太吵了', en: 'Too Noisy' },
    },
    {
        id: 'dorm',
        name: { zh: '宿舍楼', en: 'Dormitory' },
        width: 20, depth: 15, height: 35,
        color: 0xff6b6b,
        position: { x: 70, y: 0, z: -10 },
        roofType: 'flat',
        windows: { rows: 6, cols: 4 },
        mood: 'crowded',
        emotionLabel: { zh: '太拥挤了', en: 'Too Crowded' },
    },
    {
        id: 'gym',
        name: { zh: '体育馆', en: 'Gymnasium' },
        width: 35, depth: 25, height: 15,
        color: 0xe67e22,
        position: { x: 50, y: 0, z: -60 },
        roofType: 'dome',
        windows: false,
        mood: 'bare',
        emotionLabel: { zh: '想要绿色', en: 'Want More Greenery' },
    },
    {
        id: 'canteen',
        name: { zh: '食堂', en: 'Cafeteria' },
        width: 30, depth: 20, height: 12,
        color: 0xffd93d,
        position: { x: 80, y: 0, z: 40 },
        roofType: 'flat',
        windows: { rows: 2, cols: 5 },
        mood: 'monotonous',
        emotionLabel: { zh: '太单调了', en: 'Too Monotonous' },
    },
    {
        id: 'admin',
        name: { zh: '行政楼', en: 'Administration' },
        width: 22, depth: 18, height: 18,
        color: 0x34495e,
        position: { x: -80, y: 0, z: -60 },
        roofType: 'flat',
        windows: { rows: 3, cols: 5 },
    },
];

export const CAMPUS_ROADS = [
    { from: { x: -120, z: 0 }, to: { x: 120, z: 0 }, width: 12 },
    { from: { x: 0, z: -100 }, to: { x: 0, z: 100 }, width: 12 },
];

export const ROAM_WAYPOINTS = [
    { x: 80, y: 25, z: 60 },
    { x: -60, y: 25, z: 50 },
    { x: -80, y: 25, z: -30 },
    { x: 0, y: 25, z: -60 },
    { x: 60, y: 25, z: -40 },
    { x: 80, y: 25, z: 20 },
];
